### ISSUE TITLE
Angular: Unhandled Promise rejection: Cannot read property 'Symbol(Symbol.species)' of undefined ; Zone: <root>

### ISSUE THREAD

**Issue by mkurte** [single-spa/single-spa-layout#140]
Hey guys,

I'm pretty new with single-spa and still evaluating it.
I try to show some angular frontends with single-spa and it works fine except for one error I get in the developer console of chrome and firefox. I haven't tested any other browsers but I'm sure the error shows up everywhere:

```
Unhandled Promise rejection: Cannot read property 'Symbol(Symbol.species)' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'Symbol(Symbol.species)' of undefined
    at Module.e.then (zone.min.js:27)
    at k (zone.min.js:27)
    at zone.min.js:27
    at e.invokeTask (zone.min.js:13)
    at t.runTask (zone.min.js:13)
    at _ (zone.min.js:13)
    at t.invokeTask [as invoke] (zone.min.js:13)
    at p (zone.min.js:43)
    at HTMLScriptElement.h (zone.min.js:43) TypeError: Cannot read property 'Symbol(Symbol.species)' of undefined
    at Module.e.then (https://cdn.jsdelivr.net/npm/zone.js@0.11.3/dist/zone.min.js:27:4318)
    at k (https://cdn.jsdelivr.net/npm/zone.js@0.11.3/dist/zone.min.js:27:1549)
    at https://cdn.jsdelivr.net/npm/zone.js@0.11.3/dist/zone.min.js:27:2804
    at e.invokeTask (https://cdn.jsdelivr.net/npm/zone.js@0.11.3/dist/zone.min.js:13:7855)
    at t.runTask (https://cdn.jsdelivr.net/npm/zone.js@0.11.3/dist/zone.min.js:13:2934)
    at _ (https://cdn.jsdelivr.net/npm/zone.js@0.11.3/dist/zone.min.js:13:10171)
    at t.invokeTask [as invoke] (https://cdn.jsdelivr.net/npm/zone.js@0.11.3/dist/zone.min.js:13:9016)
    at p (https://cdn.jsdelivr.net/npm/zone.js@0.11.3/dist/zone.min.js:43:733)
    at HTMLScriptElement.h (https://cdn.jsdelivr.net/npm/zone.js@0.11.3/dist/zone.min.js:43:966)
```

So, somethings wrong with zone.js, and to be honest, I don't have a clue what this is. I also checked out the official angular examples from your docs page (https://github.com/angular-microfrontends) but I get the same error here.

I made a small monorepo where you can reproduce the error, you can find it here:
https://github.com/mkurte/single-spa-angular

I used Angular CLI Version 12 and create the single-spa-root config via `npx create-single-spa`.
Is there something I forgot or is this error new?

Many thanks in advance!

Cheers,
Matthias

PS: I'm not a native english speaker - so please excuse my bad english.

**Comment by mkurte** [comment]
Wrong repository.
